require 'rake/clean'

INCLUDE = "include"
#ERLC_FLAGS = "-I#{INCLUDE} +warn_unused_vars +warn_unused_import +debug_info"
ERLC_FLAGS = "-I#{INCLUDE} +debug_info"

SRC = FileList['src/*.erl']
OBJ = SRC.pathmap("%{src,ebin}X.beam")
CLEAN.include("ebin/*.beam")

directory 'ebin'

rule ".beam" =>  ["%{ebin,src}X.erl"] do |t|
  sh "erlc -pa ebin -W #{ERLC_FLAGS} -o ebin #{t.source}"
end

task :compile => ['ebin'] + OBJ
task :default => :compile

task :run => :compile do
	sh "erl -pa ebin -run jungle test -run init stop -noshell"
end

task :profile => :compile do
	sh "erl -pa ebin -run jungle profile -run init stop -noshell "
end